version: "3.7"

services:
  zinklar_challenge:
    image: node:20-alpine
    container_name: zinklar_challenge
    working_dir: "/app"
    volumes:
      - .:/app
    ports:
      - ${API_PORT}:${API_PORT}
